### ISSUE TITLE
radiant-lse fails with "fixme: package" with my up5k

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/fpga-tool-perf#7]
```
$ ./up5k.sh --verbose --fail --toolchain radiant-lse
+ set -e
+ mkdir -p build
+ exhaustive
+ echo 'Running exhaustive project-toolchain search'
Running exhaustive project-toolchain search
++ python3 fpgaperf.py --list-projects
+ for project in '$(python3 fpgaperf.py --list-projects)'
+ '[' -n murax -a murax '!=' murax ']'
++ python3 fpgaperf.py --list-toolchains
+ for toolchain in '$(python3 fpgaperf.py --list-toolchains)'
+ '[' -n radiant-lse -a radiant-lse '!=' arachne ']'
+ continue
+ for toolchain in '$(python3 fpgaperf.py --list-toolchains)'
+ '[' -n radiant-lse -a radiant-lse '!=' icecube2-lse ']'
+ continue
+ for toolchain in '$(python3 fpgaperf.py --list-toolchains)'
+ '[' -n radiant-lse -a radiant-lse '!=' icecube2-synpro ']'
+ continue
+ for toolchain in '$(python3 fpgaperf.py --list-toolchains)'
+ '[' -n radiant-lse -a radiant-lse '!=' icecube2-yosys ']'
+ continue
+ for toolchain in '$(python3 fpgaperf.py --list-toolchains)'
+ '[' -n radiant-lse -a radiant-lse '!=' nextpnr ']'
+ continue
+ for toolchain in '$(python3 fpgaperf.py --list-toolchains)'
+ '[' -n radiant-lse -a radiant-lse '!=' radiant-lse ']'
+ echo

+ run radiant-lse murax
+ toolchain=radiant-lse
+ project=murax
+ '[' project/murax_up5k-sg48.pcf = '' ']'
+ pcf_arg='--pcf project/murax_up5k-sg48.pcf'
++ python3 fpgaperf.py --list-seedable
+ [[ arachne
nextpnr
vpr = *\r\a\d\i\a\n\t\-\l\s\e* ]]
+ seed=
+ run2
+ python3 fpgaperf.py --toolchain radiant-lse --project murax --device up5k --package sg48 --seed '' --pcf project/murax_up5k-sg48.pcf --out-prefix build --verbose
Writing to build/ice40-up5k-sg48_radiant-lse_murax_default_pcf
Copying data file src/murax/Murax.v_toplevel_system_ram_ram_symbol0.bin to build/ice40-up5k-sg48_radiant-lse_murax_default_pcf/Murax.v_toplevel_system_ram_ram_symbol0.bin
Copying data file src/murax/Murax.v_toplevel_system_ram_ram_symbol2.bin to build/ice40-up5k-sg48_radiant-lse_murax_default_pcf/Murax.v_toplevel_system_ram_ram_symbol2.bin
Copying data file src/murax/Murax.v_toplevel_system_ram_ram_symbol1.bin to build/ice40-up5k-sg48_radiant-lse_murax_default_pcf/Murax.v_toplevel_system_ram_ram_symbol1.bin
Copying data file src/murax/Murax.v_toplevel_system_ram_ram_symbol3.bin to build/ice40-up5k-sg48_radiant-lse_murax_default_pcf/Murax.v_toplevel_system_ram_ram_symbol3.bin
Running: /home/tansell/fpga-tool-perf/radiant.sh --syn lse --strategy default
Running: (/home/tansell/fpga-tool-perf/radiant.sh --syn lse --strategy default) |&tee -a /home/tansell/fpga-tool-perf/radiant.sh.txt; (exit $PIPESTATUS )
  cwd: build/ice40-up5k-sg48_radiant-lse_murax_default_pcf
fixme: package
Traceback (most recent call last):
  File "fpgaperf.py", line 907, in <module>
    main()
  File "fpgaperf.py", line 904, in main
    run(args.family, args.device, args.package, args.toolchain, get_project(args.project), out_dir=args.out_dir, out_prefix=args.out_prefix, strategy=args.strategy, seed=seed, verbose=args.verbose, pcf=args.pcf)
  File "fpgaperf.py", line 790, in run
    t.run()
  File "fpgaperf.py", line 672, in run
    self.cmd(root_dir + "/radiant.sh", "--syn %s --strategy %s" % (syn, self.strategy), env=env)
  File "fpgaperf.py", line 146, in cmd
    subprocess.check_call(cmdstr, shell=True, executable='bash', cwd=self.out_dir, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(/home/tansell/fpga-tool-perf/radiant.sh --syn lse --strategy default) |&tee -a /home/tansell/fpga-tool-perf/radiant.sh.txt; (exit $PIPESTATUS )' returned non-zero exit status 1
+ false
```

**Comment by mcmasterg** [comment]
Fixed in e979fbe
